<a href="https://colab.research.google.com/github/DavRo24/learn-github/blob/master/Ago11-12/Notas-Tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introducción a Numpy

---



In [31]:
import numpy as np
x=np.random.seed(0)  #Inicio de datos random

x1 = np.random.randint(10, size=6)  #Matriz de una dimensión
x2 = np.random.randint(10, size=(3, 4))  #Matriz de dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5))  #Matriz de tres dimensiones
print(x1)
print(x2[2,3]) #Seleccionamos e imprimimos el elemento mencionado por [fila, columna]
print(x1[:2]) #:número hace que podamos leer los datos a partir de la posicón número para atrás
x1[2:]        #número: Hace lo contrario, lee los datos a partir de la posión número, tomando número en la lista
c = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([[93],
             [22]])
np.concatenate([c, y]) #concatenando vectores
g = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([g,g]))#Concatenando matríces
np.concatenate([g,g], axis=1)#Concatenando matríces pero concatena por filas
np.vstack([c,g]) #Concatenando vectores-matrices verticales
np.hstack([z,g]) #Concatenando cadenas horizontales

[5 0 3 3 7 9]
7
[5 0]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


array([[93,  1,  2,  3],
       [22,  4,  5,  6]])

##Distintas operaciones con arrays

In [34]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)
min(big_array), max(big_array)
M = np.random.random((3, 4))
print(M)
M.sum()
M.min(axis=0)
M.max(axis=1)

121 ms ± 35.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
369 µs ± 6.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[[0.88459013 0.86339669 0.14849708 0.69583359]
 [0.94857058 0.82859362 0.30826908 0.15673665]
 [0.090362   0.01082926 0.56097913 0.75643017]]


array([0.88459013, 0.94857058, 0.75643017])

##Pandas

In [41]:
import pandas as pd
datos = pd.Series([1.25, 1.5, 1.75, 2.0])
datos.values
datos.index
datos[1:3]
datos = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
datos
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Los Datos manejados por la biblioteca pandas son más fáciles de manipullar así como ya tienen varias funciones agregadas que pueden ser de mucha ayuda, en lugar de manejar todo con las funciones completas de numpy

In [45]:
population['California']
population['California':'Illinois']
pd.Series(datos)
pd.Series([2, 4, 6])
pd.Series(5, index=[100, 200, 300])


100    5
200    5
300    5
dtype: int64

Datos manipulados y convertidos en tablas, hay que leer más la documentación para poder sacar más de estos datos

In [48]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area
states = pd.DataFrame({'population': population, #Data.frame nos ayuda a hacer tablas chidas
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Hay muchas más cosas que se pueden hacer con pandas, realmente no conozco bastante, aunque pensaba que si

In [50]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [52]:
titanic.groupby('sex')[['survived']].mean() #separación de columnas y filas dependiendo a lo que se le pide

survived
sex             
female  0.742038
male    0.188908

In [54]:
titanic.pivot_table('survived', index='sex', columns='class') #Separación por secciones

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [55]:
age = pd.cut(titanic['age'], [0, 18, 80])
titanic.pivot_table('survived', ['sex', age], 'class')

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [56]:
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 80]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 80]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 80]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 80]  0.030303  0.192308

Lee bien todo esto porque nos va a servir para lo de Balleza man